// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7vkLolexv-eClez9fr-ZbR2SwbMrLqE',
    appId: '1:974581166460:web:5b0bad960620b69ef734f9',
    messagingSenderId: '974581166460',
    projectId: 'hnotes-a08d2',
    authDomain: 'hnotes-a08d2.firebaseapp.com',
    storageBucket: 'hnotes-a08d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScn83G3-RhMdtzTjYqKnoNwJqQP1Lroc',
    appId: '1:974581166460:android:44dc24c40bff9a5df734f9',
    messagingSenderId: '974581166460',
    projectId: 'hnotes-a08d2',
    storageBucket: 'hnotes-a08d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCml6TiXCCyouHcYvl7S5jwW5bL40nuouQ',
    appId: '1:974581166460:ios:51202e8bc7bd3377f734f9',
    messagingSenderId: '974581166460',
    projectId: 'hnotes-a08d2',
    storageBucket: 'hnotes-a08d2.appspot.com',
    iosBundleId: 'com.example.hnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCml6TiXCCyouHcYvl7S5jwW5bL40nuouQ',
    appId: '1:974581166460:ios:45e2b66a14cd563af734f9',
    messagingSenderId: '974581166460',
    projectId: 'hnotes-a08d2',
    storageBucket: 'hnotes-a08d2.appspot.com',
    iosBundleId: 'com.example.hnotes.RunnerTests',
  );
}
